#!/usr/bin/env bash
set -e

# we don't want to change your gopath or working directory in any way
# lets copy instead to container-only folder and do everything there
cp -a /gopath/src/. /go/src
cp -a /src/build/. /go/src/github.com/influxdata/telegraf 1>&2

git config --global --add safe.directory '*'

make deps 1>&2
make docker-telegraf 1>&2

tar -cf - telegraf
